apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulut-odev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulut-odev
  template:
    metadata:
      labels:
        app: bulut-odev
    spec:
      containers:
      - name: bulut-odev
        image: nazimcimen/bulutbilisim:v1
        ports:
        - containerPort: 8080



        

